### ISSUE TITLE
Modifiers for test data

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/dotnet-hedgehog#71]
Like `NonNegative`, `Positive`, etc.

These types do things such as restricting the kind of test data that can be generated. They can be pattern-matched on in properties as a stylistic alternative to using explicit quantification.

*(Haskell QuickCheck example shown below.)*

```haskell
prop_TakeDrop (NonNegative n) (xs :: [A]) =
  take n xs ++ drop n xs == xs
```

**Comment by moodmosaic** [comment]
Though, I think with the `property` expression this isn't really needed...

**Comment by jystic** [comment]
Having integrated shrinking means that these are redundant I think. You'd just generate the range of values that you want to begin with:
```
let! n = Gen.range 0 100
...
```

**Comment by moodmosaic** [comment]
Yeah, actually that's exactly what I ended up doing today 👍
