### ISSUE TITLE
NuGet Package

### ISSUE THREAD

**Issue by moodmosaic** [hedgehogqa/dotnet-hedgehog#72]
It'll make it a whole lot easier to use dotnet-hedgehog if we put it on NuGet. Right now it's usable mostly via Paket, as shown in [this](https://github.com/moodmosaic/dotnet-hedgehog-samples/blob/6ef760ee2dea673983bfa660b87fba3a7effb48c/Hedgeploration.fsx) sample.

If we put it on NuGet, I'd propose to also keep http://semver.org/ in mind, and start with version `0.x`, so we can be more flexible with any breaking changes we might introduce during the next couple of months.

To publish on NuGet, we need a profile on the [NuGet Gallery](https://www.nuget.org/). May I proceed by creating one for Hedgehog QA? Otherwise we could use @jystic's or the [one I use](https://www.nuget.org/profiles/moodmosaic) already?

**Comment by jystic** [comment]
> May I proceed by creating one for Hedgehog QA?

Yep, go for it 👍 

Would be good if we can both have access eventually, so maybe you could figure out how that would work. Happy for you to look after it for the time being though.

**Comment by jystic** [comment]
(I'll get to your PRs on the weekend btw)

**Comment by moodmosaic** [comment]
>Would be good if we can both have access eventually

Sure, I think that's easy, if we create an account with some `hedgehog.qa` email that both have access to.

(Once the account is created, we set the profile picture to the SQUARE_hedgehog_300x300.png logo, and then copy the API key, so we can push from our local machines.)

**Comment by moodmosaic** [comment]
Resolved by #73 and #77.
